### ISSUE TITLE
Please add a 'Prerequisites' section in the README

### ISSUE THREAD

**Issue by luzpaz** [tomster/FreeCAD-lumberjack#1]
To highlight that this WB requires Link branch and A3 WB...

**Comment by tomster** [comment]
It’s literally the second sentence in the first paragraph: “ It has been written specifically for the Assembly3 Workbench and the socalled Linkstage Fork of FreeCAD.”

**Comment by luzpaz** [comment]
Indeed. I saw that. Just out of experience with documentation and READMEs - it's a lot more helpful to highlight this point.
